### ISSUE TITLE
mission diff crashes on comparing opened & saved TTI 1.80a

### ISSUE THREAD

**Issue by MansM** [pydcs/dcs#116]
Application code:
```python
import dcs

mission = dcs.Mission()
#renamed file to cauc.miz as load doesnt like spaces
mission.load_file(filename="cauc.miz")
mission.save("out.miz")
```
running compare
```
$ python venv/src/dcs/tools/missiondiff.py cauc.miz out.miz
WARNING : Trying to run pydcs on non Windows machine
Couldn't detect any installed DCS World version
Traceback (most recent call last):
  File "compare.py", line 31, in <module>
    main()
  File "compare.py", line 28, in main
    print(diff(missionA, missionB))
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 276, in diff_dict
    nested_diff = diff(a[key], b[key], context, depth+1)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 72, in diff
    return diff_dict(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/Users/username/Documents/projecten/dcs-pipeline/venv/lib/python3.8/site-packages/datadiff/__init__.py", line 301, in diff_dict
    ddiff.diffs.sort(key=diffitem_dictitem_sort_key)
TypeError: '<' not supported between instances of 'str' and 'int'
(venv)
```

```
$ python -V
Python 3.8.7
```

**Comment by rp-** [comment]
I didn't use or update the mission-diff for some time, it was used in the early development to check for missing parts/diffs.
Not sure if I get enough time to update it, but PR's are always welcome
