### ISSUE TITLE
Unit Group name throwing AttributeError for DCS 2.7 mission saved in editor

### ISSUE THREAD

**Issue by ColinM9991** [pydcs/dcs#134]
Here is a stack trace for an error that occurs when I attempt to save a mission which has previously been saved via the editor for 2.7. It appears the unit name is still an issue.

To reproduce, download this mission and save it via the editor, then try to use pydcs to open edit and re-save.
https://www.digitalcombatsimulator.com/en/files/3313323/

```
Traceback (most recent call last):
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "<server_path>\Desktop\Bot\cogs\dcsmissioncog.py", line 47, in set_weather
    dcs_mission.save()
  File "<server_path>\Desktop\Bot\helpers\dcsmissioneditor.py", line 107, in save
    self.mission.save()
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\mission.py", line 1907, in save
    zipf.writestr('mission', str(self))
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\mission.py", line 1979, in __str__
    return lua.dumps(self.dict(), "mission", 1)
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\mission.py", line 1956, in dict
    m["coalition"][col] = self.coalition[col].dict()
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\coalition.py", line 291, in dict
    d["country"][i] = self.country(country).dict()
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\country.py", line 194, in dict
    d["plane"]["group"][i] = plane_group.dict()
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\unitgroup.py", line 514, in dict
    d = super(FlyingGroup, self).dict()
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\unitgroup.py", line 253, in dict
    d = super(MovingGroup, self).dict()
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\dcs\unitgroup.py", line 183, in dict
    "name": self.name.id,
AttributeError: 'str' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "<server_path>\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'id'
```

**Comment by rp-** [comment]
Thanks for finding this I started my own PR with a few more changes for that issues, see: #136
