### ISSUE TITLE
Vehicle 'transportable' property absent during import

### ISSUE THREAD

**Issue by spencershepard** [pydcs/dcs#214]
This occurred after adding vehicles in the mission editor with 2.7.11.21408.1

From the DCS 2.7.11.21408.1 Open Beta changelog:
"ME. Mission editor does not read Transportable boolean when opening .miz file - fixed."

My error:
Traceback (most recent call last): File "C:\RotorOps\Generator\MissionGenerator.py", line 208, in scenarioChanged source_mission.load_file(filename) File "c:\rotorops\generator\venv\src\pydcs\dcs\mission.py", line 376, in load_file status += self.coalition[col_name].load_from_dict(self, imp_mission["coalition"][col_name]) File "c:\rotorops\generator\venv\src\pydcs\dcs\coalition.py", line 114, in load_from_dict unit.load_from_dict(imp_unit) File "c:\rotorops\generator\venv\src\pydcs\dcs\unit.py", line 78, in load_from_dict self.transportable = d["transportable"] KeyError: 'transportable'

**Comment by rp-** [comment]
Hi!

It would always be good, if you could attach such a mission for testing

**Comment by spencershepard** [comment]
[transportable error miz.zip](https://github.com/pydcs/dcs/files/8302191/transportable.error.miz.zip)

Hi there, okay yes no problem.  Attached is an original miz, created before the DCS update.  I opened this in the mission editor, latest DCS version after today's update, and saved it as a new file.  This one shows the error I described.  Also attached.  

Thanks!

**Comment by DanAlbert** [comment]
If you have the time to test with https://github.com/pydcs/dcs/pull/215, I can merge that. I haven't been able to test it much yet but it seems plausible.

**Comment by spencershepard** [comment]
It seems to solve my issues from a quick test.  Thanks guys
