### ISSUE TITLE
mission.load() on syria fails, likely due to undefined warehouse-airport pairs.

### ISSUE THREAD

**Issue by Zonr0** [pydcs/dcs#223]
Attempting to use the `mission.load()` API fails due to a NoneType error being raised. Example traceback:

```
Traceback (most recent call last):
  File "C:\Users\ZonrZ\PycharmProjects\DCSDynamic\main.py", line 16, in <module>
    didLoad = m.load_file(BASE_MISSION_PATH)
  File "C:\Users\ZonrZ\PycharmProjects\DCSDynamic\venv\lib\site-packages\dcs\mission.py", line 300, in load_file
    self.warehouses.load_dict(warehouse_dict["warehouses"])
  File "C:\Users\ZonrZ\PycharmProjects\DCSDynamic\venv\lib\site-packages\dcs\terrain\terrain.py", line 502, in load_dict
    self.terrain.airport_by_id(x).load_from_dict(data["airports"][x])
AttributeError: 'NoneType' object has no attribute 'load_from_dict'
```

The exception occurs in the following code when `x` is 5.

```
    def load_dict(self, data):
        for x in data.get("airports", {}):
            self.terrain.airport_by_id(x).load_from_dict(data["airports"][x])
```

After some investigation, I have a working theory on why this is happening. Looking through the airport list, there is no airport ID defined for 5. The closest are An Nasiriyah at 4, and Beirut Rafic Hariri at 6. However, there is a warehouse with no airport on the Syria map named At Tanf, which is presumably warehouse ID 5 if they're ID'd in alphabetical order. There is another warehouse on the Syria map like this (Karab Ishk), along with several tiny airports with warehouse (not not airport) icons that do not appear to show up in the Syria terrain definition. On closer inspection, it looks like the Cypress airports may not be defined either, so it may just be that the definitions are missing some of the recent expansions.

A full proper fix would might require some special handling for the two warehouses not attached to an airport at all and maybe for the tiny airports too small for any in-game aircraft. Either way, it seems like the definition file needs some work. It would also be nice to have some kind of fallback behavior for now so that load_mission still works when it encounters undefined airport IDs. Would it be reasonable to just return a special 'null' airport with the relevant fields initialized to zero, and a new isDefined field set to false?

**Comment by Zonr0** [comment]
Just tested this on the latest commit on master instead of the version on pypi. It appears to be resolved. Guess that serves me right for not double checking the version first!
