### ISSUE TITLE
Missing Task 'FireAtPoint'

### ISSUE THREAD

**Issue by Igneous01** [pydcs/dcs#31]
There appears to be no way to add a FireAtPoint task, and when loading a mission file that has this defined, it throws an error when loading.

`
Traceback (most recent call last):
  File "C:/Users/U/PycharmProjects/dcs_dnd_campaign/test.py", line 4, in <module>
    successLoad = m.load_file('C:\\Users\\U\\Saved Games\\DCS\\Missions\\dcs_dnd_campaign\\dcs_dnd_campaign_turn_01R_After_Sortie_1.miz')
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\mission.py", line 342, in load_file
    self.coalition[col_name].load_from_dict(self, imp_mission["coalition"][col_name])
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\coalition.py", line 50, in load_from_dict
    Coalition._import_moving_point(mission, vg, vgroup)
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\coalition.py", line 24, in _import_moving_point
    point.load_from_dict(imp_point, mission.translation)
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\point.py", line 132, in load_from_dict
    self.tasks.append(task._create_from_dict(d["task"]["params"]["tasks"][t]))
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\task.py", line 26, in _create_from_dict
    t = tasks_map[_id].create_from_dict(d)
KeyError: 'FireAtPoint'
`

**Comment by rp-** [comment]
loading should be fixed with: 23228a2132655039bf8ce297312a79a373925f2c

creating FireAtPoint task was working before, just add a FireAtPoint task to a waypoint
