### ISSUE TITLE
import dcs fails

### ISSUE THREAD

**Issue by kaitsu71** [pydcs/dcs#325]
Probably a stupid question but I cannot figure out why with this test.py code:

**import dcs
m = dcs.Mission()
m.save('mission.miz')**

I get this error:

**C:\Users\Kai\Saved Games\DCS.openbeta\Missions\pydcs>python test.py
Traceback (most recent call last):
  File "C:\Users\Kai\Saved Games\DCS.openbeta\Missions\pydcs\test.py", line 1, in <module>
    import dcs
  File "C:\Users\Kai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dcs\__init__.py", line 1, in <module>
    from . import mission
... 
    from dcs.terrain.caucasus.caucasus import Caucasus
  File "C:\Users\Kai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dcs\terrain\caucasus.py", line 8, in <module>
    class Anapa_Vityazevo(Airport):
  File "C:\Users\Kai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dcs\terrain\caucasus.py", line 11, in Anapa_Vityazevo
    position = mapping.Point(-5412.409668, 243128.820313)
TypeError: Point.__init__() missing 1 required positional argument: 'terrain'**

**Comment by DanAlbert** [comment]
That looks like a corrupt install from multiple versions of pydcs? The caucasus.py file in the last line of the trace was deleted a while back. I'm guessing the stale file got left behind when the new version was installed?

**Comment by kaitsu71** [comment]
Yeah, that was it! I have done "pip install pydcs" every now and then and looks the installation got corrupted at some point. I just said "pip uninstall pydcs" and "pip install pydcs" now and it is working. Thank you!
